version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Debug

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" tests\01-hello-world

build:
  project: $(APPVEYOR_BUILD_FOLDER)\01-hello-world.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\01-hello-world.exe'