image: leanid/fedora26
pipelines:
  default:
    - step:
        script:
          - git clean -df
          - cmake -configure tests/01-hello-world/
          - cmake -generate tests/01-hello-world/
          - make
          - ./01-hello-world
          
          - git clean -df
          - mingw64-cmake -configure tests/01-hello-world/
          - mingw64-cmake -generate tests/01-hello-world/
          - mingw64-make
          #- WINEPATH=/usr/x86_64-w64-mingw32/sys-root/mingw/bin wine ./01-hello-world.exe # too long 30 seconds
          
          - git clean -df
          - CXX=clang++ cmake -configure tests/01-hello-world/
          - CXX=clang++ cmake -generate tests/01-hello-world/
          - make
          - ./01-hello-world

          - git clean -df
          - cmake -configure tests/02-sdl-dynamic/
          - cmake -generate tests/02-sdl-dynamic/
          - make
          - ./02-sdl-dynamic

          - git clean -df
          - cmake -configure tests/02-sdl-static/
          - cmake -generate tests/02-sdl-static/
          - make
          - ./02-sdl-static

          - git clean -df
          - mingw64-cmake -configure tests/02-sdl-dynamic/
          - mingw64-cmake -generate tests/02-sdl-dynamic/
          - mingw64-make
          #- WINEPATH=/usr/x86_64-w64-mingw32/sys-root/mingw/bin wine ./02-sdl-dynamic.exe # too long 30 seconds

          - git clean -df
          - mingw64-cmake -configure tests/02-sdl-static/
          - mingw64-cmake -generate tests/02-sdl-static/
          - mingw64-make
          #- WINEPATH=/usr/x86_64-w64-mingw32/sys-root/mingw/bin wine ./02-sdl-static.exe # too long 30 seconds
         
          - git clean -df
          - mingw64-cmake -configure tests/04-opengl-minimal/
          - mingw64-cmake -generate tests/04-opengl-minimal/
          - mingw64-make
          #- WINEPATH=/usr/x86_64-w64-mingw32/sys-root/mingw/bin wine ./game.exe # run opengl minimal on linux with wine (works)
